version: "3.3"

services:

   site:
      image: tekton/website
      build:
         context: .
      ports: 
         - "8888:8888"
      volumes:
         - /src/content/en/docs/Reference/
         - /src/content/en/vault/
         - /src/node_modules/
         - .:/src/
